name: Npm package

on:
  push:
    branches:
      - '*'
    tags:
      - v*

jobs:
  deploy:
    if: contains(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Nodejs 10.16.3
        uses: actions/setup-node@master
        with:
          version: 10.16.3

      - name: Publish to Npm
        run: |
          cd js-plugins
          echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> .npmrc
          npm publish
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
